-- Create profiles table
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  role text check (role in ('user', 'admin')) default 'user',
  full_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;

-- Create tickets table
create table public.tickets (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  status text check (status in ('Open', 'In Progress', 'Resolved')) default 'Open',
  priority text check (priority in ('Low', 'Medium', 'High')) default 'Medium',
  created_by uuid references public.profiles(id) not null,
  assigned_to uuid references public.profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.tickets enable row level security;

-- Create comments table
create table public.comments (
  id bigint generated by default as identity primary key,
  ticket_id bigint references public.tickets(id) on delete cascade not null,
  user_id uuid references public.profiles(id) not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.comments enable row level security;

-- Policies (Simple for now, can be refined)
-- Profiles: Users can view their own profile. Admins can view all.
create policy "Public profiles are viewable by everyone"
  on profiles for select
  using ( true );

create policy "Users can insert their own profile"
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile"
  on profiles for update
  using ( auth.uid() = id );

-- Tickets: Users can view their own tickets. Admins can view all.
create policy "Users can view own tickets"
  on tickets for select
  using ( auth.uid() = created_by );

create policy "Admins can view all tickets"
  on tickets for select
  using ( exists (select 1 from profiles where id = auth.uid() and role = 'admin') );

create policy "Users can create tickets"
  on tickets for insert
  with check ( auth.uid() = created_by );

create policy "Users can update own tickets"
  on tickets for update
  using ( auth.uid() = created_by );

create policy "Admins can update all tickets"
  on tickets for update
  using ( exists (select 1 from profiles where id = auth.uid() and role = 'admin') );

-- Comments: Viewable by ticket creator and admins.
create policy "Comments viewable by ticket owner and admins"
  on comments for select
  using (
    exists (select 1 from tickets where id = ticket_id and created_by = auth.uid())
    or
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

create policy "Users can create comments on own tickets"
  on comments for insert
  with check (
    exists (select 1 from tickets where id = ticket_id and created_by = auth.uid())
  );

create policy "Admins can create comments"
  on comments for insert
  with check ( exists (select 1 from profiles where id = auth.uid() and role = 'admin') );
